### ISSUE TITLE
Command crashes when trying to add a malformed source

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/repolib#55]
```
system76@pop-os:~$ apt-manage add pop-dev:isolate-workspaces
Fetching repository information...
Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 82, in <module>
    main()
  File "/usr/bin/apt-manage", line 76, in main
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 155, in run
    new_source.load_from_data([self.deb_line])
UnboundLocalError: local variable 'new_source' referenced before assignment
```

**Comment by isantop** [comment]
The shortcut is `popdev:` not `pop-dev:`. The error handling could definitely be improved though.

**Comment by 13r0ck** [comment]
Ah thanks!

I agree with you, this is still an error handling bug. It shouldn't crash, a "reasonably" helpful error should be provided before closing
